%% -*- mode: erlang -*-
IsWin32 = fun() ->
    win32 =:= element(1, os:type())
end,

Bcrypt = {bcrypt, {git, "https://github.com/emqx/erlang-bcrypt.git", {tag, "0.6.2"}}},

ExtraDeps = fun(C) ->
    {deps, Deps0} = lists:keyfind(deps, 1, C),
    {erl_opts, ErlOpts0} = lists:keyfind(erl_opts, 1, C),
    New = [
        {deps, Deps0 ++ [Bcrypt || not IsWin32()]},
        {erl_opts, ErlOpts0 ++ [{d, 'BUILD_WITHOUT_QUIC'}]}
    ],
    lists:foldl(
        fun({Key, _Val} = KV, Acc) ->
            lists:keystore(Key, 1, Acc, KV)
        end,
        C,
        New
    )
end,

ExtraDeps(CONFIG).
