%% -*- mode: erlang -*-
Backends = [emqx_ds_builtin_local],

io:format(user, "DS backends available for this release: ~0p~n", [Backends]),

{application, emqx_ds_backends, [
    {description, "A placeholder application that depends on all available DS backends"},
    % strict semver, bump manually!
    {vsn, "0.1.0"},
    {modules, []},
    {registered, []},
    {applications, [kernel, stdlib, emqx_durable_storage | Backends]},
    {env, [{available_backends, Backends}]}
]}.
